config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#index'
  resources :pages do
    resource :likes, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '寺社' },
    { id: 2, name: '城' },
    { id: 3, name: 'レストラン・カフェ' },
    { id: 4, name: 'フォトスポット' },
    { id: 5, name: '図書館' },
    { id: 6, name: 'お店' },
    { id: 7, name: '博物館・美術館' },
    { id: 8, name: '海・プール' },
    { id: 9, name: '山' },
    { id: 10, name: '温泉・スパ' },
    { id: 11, name: '動植物園・水族館' },
    { id: 12, name: '道の駅・PA' },
    { id: 13, name: '公園' },
    { id: 14, name: 'プラネタリウム' },
    { id: 15, name: 'イベント・映画' }
  ]

  include ActiveHash::Associations
  has_many :spots
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :page

  validates_uniqueness_of :page_id, scope: :user_id
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :user

  has_many :spots, dependent: :destroy, inverse_of: :page
  accepts_nested_attributes_for :spots, allow_destroy: true, reject_if: :all_blank
  validates_associated :spots

  has_many :likes, dependent: :destroy

  validates :page_title, presence: true

  acts_as_taggable

end

app/models/page_spot.rb
class PageSpot
  include ActiveModel::Model
  
  attr_accessor :
end

app/models/spot.rb
class Spot < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  belongs_to :page

  validates :spot_name, presence: true
  validates :spot_address, presence: true
  validates :category_id, numericality: { other_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image

  validates :nickname, presence: true

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください'

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates_format_of :email, with: EMAIL_REGEX, message: 'には＠を含んでください'

  has_many :pages
  has_many :likes, dependent: :destroy

  def already_liked?(page)
    likes.exists?(page_id: page.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :user_text, :image])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_page, only: [:create, :destroy]

  def create
    @like = current_user.likes.create(page_id: @page.id)
  end

  def destroy
    @like = current_user.likes.find_by(page_id: @page.id)
    @like.destroy!
  end

  private

  def set_page
    @page = Page.find(params[:page_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_page, only: [:destroy, :edit, :update]

  def index
    @pages = Page.order('created_at DESC').limit(3)
    if params[:tag_name]
      @pages = Page.tagged_with("#{params[:tag_name]}")
    end
  end

  def new
    @page = Page.new
    @page.spots.build
  end

  def create
    @page = Page.new(page_params)
    if @page.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @page = Page.where(id: params[:id])
  end

  def destroy
    @page.destroy
    redirect_to root_path
  end

  def edit
  end

  def update
    if @page.update(page_params)
      redirect_to action: :show
    else
      render :edit
    end
  end

  private

  def page_params
    params.require(:page).permit(:page_title, :page_comment, :tag_list,
                                 spots_attributes: [:id, :spot_name, :spot_address, :spot_tel, :spot_parking, :spot_comment, :_destroy, :page_id, :category_id]).merge(user_id: current_user.id)
  end

  def set_page
    @page = Page.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tyorippu2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V" crossorigin="anonymous">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/_like.html.erb
<% if user_signed_in? %>
  <% if current_user.already_liked?(page) %>
    <%= link_to page_likes_path(page), method: :delete, remote: true, id: "unlike_btn" do %>
      <i class="far fa-kiss-wink-heart unlike_btn"></i>
    <% end %>
    <%= page.likes.count %>
  <% else %>
    <%= link_to page_likes_path(page), method: :post, remote: true, id: "like_btn" do %>
      <i class="far fa-kiss like_btn"></i>
    <% end %>
    <%= page.likes.count %>
  <% end %>
<% else %>
  <i class="far fa-kiss"></i>
  <%= page.likes.count %>
<% end %>

app/views/likes/create.js.erb
$('#likes_btn_<%= @page.id %>').html("<%= j(render partial: 'likes/like', locals: {page: @page, like: @like}) %>");

app/views/likes/destroy.js.erb
$('#unlikes_btn_<%= @page.id %>').html("<%= j(render partial: 'likes/like', locals: { page: @page, like: @like }) %>");

app/views/pages/_page_spot_fields.html.erb
<div class="nested-fields">
  <%= f.hidden_field :id %>
  <div class="field">
    <%= f.text_field :spot_name, class:"input-default", id:"spot-name", placeholder:"※ 場所の名前" %>
  </div>
  <div class="field">
    <%= f.text_area :spot_address, class:"input-default", id:"spot-address", placeholder:"※ 住所（都道府県は絶対に入力してください）" %>
  </div>
  <div class="field">
    <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"input-default", id:"spot-category"}) %>
  </div>
  <div class="field">
    <%= f.text_field :spot_tel, class:"input-default", id:"spot-tel", placeholder:"電話番号" %>
  </div>
  <div class="field">
    <%= f.label :spot_parking, "※ 駐車場：" %>
    <%= f.radio_button :spot_parking, "なし", checked: true %>なし
    <%= f.radio_button :spot_parking, "あり" %>あり
    <%= f.radio_button :spot_parking, "近隣に有料あり" %>近隣に有料あり
  </div>
  <div class="field">
    <%= f.text_field :spot_comment, class:"input-default", id:"spot-comment", placeholder:"あなたの感想をひとことどうぞ！" %>
  </div>
  <%= link_to_remove_association "remove spot", f %>
</div>

app/views/pages/_tag_list.html.erb
<% tag_list.each do |tag| %>
  <i class="fas fa-tag"></i>
  <%= link_to tag, pages_path(tag_name: tag) %>
<% end %>

app/views/pages/edit.html.erb
<%= render "shared/second_header" %>
<div class='main'>

  <div class="page-spots-contents">

    <%= form_with(model: @page, url: page_path, method: :patch, local: true ) do |f| %>
      <%= render 'shared/error_messages', model: @page %>
      
      <%# ページ情報部分 %>
      <h3 class="info-input-headline">ページ情報</h3>
          <div class="field">
            <%= f.text_field :page_title, class:"input-default", id:"page-name", placeholder:"※ ページタイトルは？", maxlength:"40" %>
          </div>
          <div class="field">
            <%= f.text_field :page_comment, class:"input-default", id:"page-comment", placeholder:"どんなコースかひとことでどうぞ！", maxlength:"40" %>
          </div>
      <%# ページ情報部分 %>

      <%# タグ情報 %>
      <div class="field">
        <%= f.label :tag_list, "タグは半角スペースか（、）で区切ってください" %>
        <%= f.text_field :tag_list, value: @page.tag_list, class:"input-default" %>
      </div>
      <%# タグ情報 %>

      <%# スポット情報 %>
      <div class='spot-form'>
        <h3 class='info-input-headline'>
          スポット情報
        </h3>
        <div id="spots">
          <%= f.fields_for :spots do |spot| %>
            <%= render 'pages/page_spot_fields', f: spot %>

          <% end %>

          <div id="detail-association-insertion-point"></div>


            <%= link_to_add_association "スポット追加", f, :spots,
              partial: 'pages/page_spot_fields',
              class:"btn btn-default",
              data: {
                association_insertion_node: '#detail-association-insertion-point',
                association_insertion_method: 'append'
              }
            %>
        </div>
      </div>
      <%# スポット情報 %>

      <%# 更新ボタン %>
      <div class="rewrite-btn">
        <%= f.submit "Rewrite", class:"submit-send-btn" %>
      </div>
      <%# 更新ボタン %>
    <% end %>
  </div>
</div>

app/views/pages/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# 画面上部の「ちょりっぷ」帯部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      ちょりっぷ
    </h2>
    <p class='service-explain'>
      「ちょっとそこまでお出かけしようかな」
    </p>
    <p class='service-explain'>
      そんなちょっとのお出かけの記録アプリです
    </p>
  </div>
  <%# /画面上部の「ちょりっぷ」帯部分  %>


  <%# 投稿一覧 %>
  <div class='page-contents'>
    <h2 class='title'>ピックアップ</h2>
    <div class="subtitle" >
      NEW course!
    </div>
    
    <ul class='page-lists'>
      <%# 投稿内容 %>
      <% @pages.each do |page| %>
      <li class='list'>
        <%= link_to page_path(page.id) do %>
        <div class='page-spot-img-content'>
          <%= image_tag "sky1.png", class: "page-img" %>
        </div>

        <div class='page-info'>
            <h3 class='page-name'>
              <%= page.page_title %>
            </h3>
            <div class='page-comment'>
              <span><%= page.page_comment %></span>

              <div id='like_btn_<%= page.id %>', class='like'>
                <%= render 'likes/like', page: page, likes: @likes %>
              </div>

            </div>
          </div>
        <% end %>
      <% end %>


      <%# ページが一つもない場合の表示 %>
      <% if @pages.empty? %>
        <li class='list'>
          <%= link_to '#' do %>
          <%= image_tag "sky1.png", class: "page-img" %>
          <div class='page-info'>
            <h3 class='page-name'>
              コースを記録しましょう！
            </h3>
            <div class='page-comment'>
              <span>楽しい１日を！！</span>
            </div>
          </div>
          <% end %>
        </li>
      <% end %>
      <%# ページが一つもない場合の表示 %>

      <%# //投稿内容 %>
    </ul>
  </div>
  <%# 投稿一覧 %>
</div>

<%# 投稿ボタン %>
<%= link_to(new_page_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>投稿する</span>
  <%= image_tag 'write-icon.png' , class: "purchase-btn-icon" %>
<% end %>
<%# 投稿ボタン %>

<%= render "shared/footer" %>

<script>
$(".like").click(function(){
    location.reload();
})
</script>

app/views/pages/new.html.erb
<div class="page-spots-contents">
  <header class="page-spots-header">
    <%= link_to image_tag('tyorippu_logo.png', size: '100x80'), root_path %>
  </header>
  <div class="page-spots-main">
    <h2 class="page-spots-title">コースを記録</h2>
    <p class="caution">
      ※がある部分は必須項目です
    </p>
    <%= form_with(model: @page, local: true ) do |f| %>
      <%= render 'shared/error_messages', model: f.object %>

      <%# page情報 %>
      <h3 class="info-input-headline">ページ情報</h3>
      <div class="field">
        <%= f.text_field :page_title, class:"input-default", id:"page-name", placeholder:"※ ページタイトルは？", maxlength:"40" %>
      </div>
      <div class="field">
        <%= f.text_field :page_comment, class:"input-default", id:"page-comment", placeholder:"どんなコースかひとことでどうぞ！", maxlength:"40" %>
      </div>
      <%# page情報 %>

      <%# tag情報 %>
      <div class="field">
        <%= f.label :tag_list, "タグは半角スペースか（、）で区切ってください" %>
        <%= f.text_field :tag_list, value: @page.tag_list, class:"input-default" %>
      </div>
      <%# tag情報 %>

      <%# ページのメイン部分 %>
      <div class='spot-form'>
        <h3 class='info-input-headline'>
          スポット情報
        </h3>

        <%# spotテーブル %>
        <div id="spots">
          <%= f.fields_for :spots do |spot| %>
            <%= render 'pages/page_spot_fields', f: spot %>

            <div id="detail-association-insertion-point"></div>
          <% end %>


            <%= link_to_add_association "スポット追加", f, :spots,
              partial: 'pages/page_spot_fields',
              class:"btn btn-default",
              data: {
                association_insertion_node: '#detail-association-insertion-point',
                association_insertion_method: 'after'
              }
            %>
        </div>
        <%# spotテーブル %>
      
        <%# 送信ボタン %>
        <%= f.submit "Send", class:"submit-send-btn" %>
    <% end %>
        <%# 送信ボタン %>
      <%# ページのメイン部分 %>
</div>

app/views/pages/show.html.erb
<div class="head-contents">
  <%= link_to root_path do %>
    <%= image_tag "sun.png", class: "sun-img" %>
  <% end %>
</div>
<div class="main">
  <div class="page-show-contents">

    <% @page.each do |page| %>
      <%# ページ情報部分 %>
      <div class="page-top-contents-left">
        <h2 class="show-page-title">
          <%= page.page_title %>
        </h2>
        <div class="show-page-comment">
          <%= page.page_comment %>
        </div>

        <div class="page-top-contents-right">
          <div class="page-user">
            <%= page.user[:nickname] %>
          </div>
          <div class="updated">
            <%= page.updated_at.strftime("%Y.%m.%d") %>
          </div>
        </div>

        <div id='like_btn_<%= page.id %>', class='like'>
          <%= render 'likes/like', page: page, likes: @likes %>
        </div>

        <%# タグ情報 %>
        <div class="tag_lists">
          <%= render 'pages/tag_list', tag_list: page.tag_list %>
        </div>
        <%# タグ情報 %>
      </div>

      <div class="edit-btn">
        <% if page.user_id == current_user.id %>
          <%# 削除ボタン %>
          <div class="delete-btn">
            <%= link_to page_path, method: :delete, class: "page-destroy" do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
          </div>

          <%# 編集ボタン %>
          <div class="rewrite-btn">
            <%= link_to edit_page_path, method: :get, class: "page-edit" do %>
              <i class="fas fa-edit"></i>
            <% end %>
          </div>
        <% end %>
      </div>
      <%# ページ情報部分 %>

      <%# スポット情報部分 %>
      <ul class="timeline">
        <div class="spot-contents">
          <% page.spots.each do |spot| %>
          <li>
            <dl>
            <div class="spot-box">
              <div class="show-spot-name">
                <%= spot.spot_name %><br>
              </div>
              <i class="fas fa-map-marker-alt"></i>
              <%= spot.spot_address %><br>
              <i class="far fa-bookmark"></i>
              <%= spot.category.name %><br>
              <i class="fas fa-phone"></i>
              <%= spot.spot_tel %><br>
              <i class="fas fa-parking"></i>
              <%= spot.spot_parking %><br>
              <i class="far fa-comment"></i>
              <%= spot.spot_comment %>
            </div>
            </dl>
            <span class="border-line"></span>
          </li>
          <% end %>
        </div>
        </ul>
      <%# スポット情報部分 %>
    <% end %>
  </div>
</div>
<div class="foot-contents">
  <%= link_to root_path do %>
    <div class="caption">TOP PAGE</div>
  <% end %>
</div>

<script>
$(".like").click(function(){
    location.reload();
})
</script>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
      <li class="error-message"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class='footer'>
  <div class='footer-contents'>
    <div class='tyorippu-details'>
      <h2 class='footer-content-head'>ちょりっぷを見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='tyorippu-details'>
      <h2 class='footer-content-head'>ちょりっぷについて</h2>
      <ul>
        <li><%= link_to 'ちょりっぷガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'ちょりっぷロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("tyorippu_logo.png", class:"logo-white"), "#" %>
  <p>© ちょりっぷ</p>
</div>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <%= link_to image_tag("tyorippu_logo.png", class:"tyorippu-icon"), "/" %>
  <div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to 'カテゴリー', "#", class: "category-list" %></li>
    </ul>
    <ul class='lists-right'>
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, "#", class: "user-nickname" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>ちょりっぷガイド</p>
    <p class='second-fotter-text'>ちょりっぷ利用規約</p>
  </div>
  <%= image_tag "tyorippu_logo.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("tyorippu_logo.png", class:"second-logo"), "/" %>
</header>

app/views/shared/_second_footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>ちょりっぷガイド</p>
    <p class='second-fotter-text'>ちょりっぷ利用規約</p>
  </div>
  <%= image_tag "tyorippu_logo.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second_header.html.erb
<header class='second-header'>
  <%= link_to image_tag("tyorippu_logo.png", class:"second-logo"), "/" %>
</header>